### ISSUE TITLE
CacheFragmentStatePagerAdapter crashes App

### ISSUE THREAD

**Issue by rafattouqir** [ksoichiro/Android-ObservableScrollView#50] opened 2015-01-18 12:12 UTC
When I used Viewpager , it works for ObservableListView,RecyclerView etc

but when the phone sleeps automatically then it crashes due to the cause of -
CacheFragmentStatePagerAdapter.saveState
android.support.v4.app.FragmentManagerImpl.putFragment .

I've tested your example "ViewPagerTabFragmentActivity" even it also crashes when viewpager is at recyclerview fragment page .
App doesn't crash at any other ObservableView rather than RecyclerView.

I tried to describe more so that it would be easy for you to solve the problem .

Thanks for your excellent library.

**Comment by PankovSerge** [comment] 2015-01-19 16:01
Have the same issue on device with 4.1.2, lollipop 5.0.2 - same , sample application -  observablescrollview-samples. 
Android Studio - 1.1, build tools 21.1.2, 
To reproduce issue:
1. Open sample application
2. Select ViewPagerTab2Activity
3. Scroll left to first GridViewFragment
4. Tap Multitasking button or Home button
5. Get error 

01-19 18:59:04.559  26933-26933/com.github.ksoichiro.android.observablescrollview.samples.debug E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.NullPointerException
            at android.support.v4.app.FragmentManagerImpl.putFragment(FragmentManager.java:570)
            at com.github.ksoichiro.android.observablescrollview.CacheFragmentStatePagerAdapter.saveState(CacheFragmentStatePagerAdapter.java:59)
            at android.support.v4.view.ViewPager.onSaveInstanceState(ViewPager.java:1270)
            at android.view.View.dispatchSaveInstanceState(View.java:12076)
            at android.view.ViewGroup.dispatchSaveInstanceState(ViewGroup.java:2634)
            at android.view.ViewGroup.dispatchSaveInstanceState(ViewGroup.java:2640)
            at android.view.ViewGroup.dispatchSaveInstanceState(ViewGroup.java:2640)
            at android.view.ViewGroup.dispatchSaveInstanceState(ViewGroup.java:2640)
            at android.view.ViewGroup.dispatchSaveInstanceState(ViewGroup.java:2640)
            at android.view.ViewGroup.dispatchSaveInstanceState(ViewGroup.java:2640)
            at android.view.View.saveHierarchyState(View.java:12059)
            at com.android.internal.policy.impl.PhoneWindow.saveHierarchyState(PhoneWindow.java:1607)
            at android.app.Activity.onSaveInstanceState(Activity.java:1198)
            at android.support.v4.app.FragmentActivity.onSaveInstanceState(FragmentActivity.java:523)
            at android.app.Activity.performSaveInstanceState(Activity.java:1147)
            at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1222)
            at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:3291)
            at android.app.ActivityThread.handleStopActivity(ActivityThread.java:3357)
            at android.app.ActivityThread.access$900(ActivityThread.java:156)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1367)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:153)
            at android.app.ActivityThread.main(ActivityThread.java:5293)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by MinsungHuh** [comment] 2015-01-20 02:21
I also same issue
I think that if fragment manager is null, appeared error code.

11233-11233/com.leeleem.storeking E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.leeleem.storeking, PID: 11233
    java.lang.NullPointerException
            at android.support.v4.app.FragmentManagerImpl.putFragment(FragmentManager.java:570)
            at com.github.ksoichiro.android.observablescrollview.CacheFragmentStatePagerAdapter.saveState(CacheFragmentStatePagerAdapter.java:59)
            at android.support.v4.view.ViewPager.onSaveInstanceState(ViewPager.java:1270)
            at android.view.View.dispatchSaveInstanceState(View.java:12859)
            at android.view.ViewGroup.dispatchSaveInstanceState(ViewGroup.java:2609)
            at android.view.ViewGroup.dispatchSaveInstanceState(ViewGroup.java:2615)
            at android.view.ViewGroup.dispatchSaveInstanceState(ViewGroup.java:2615)
            at android.view.ViewGroup.dispatchSaveInstanceState(ViewGroup.java:2615)
            at android.view.ViewGroup.dispatchSaveInstanceState(ViewGroup.java:2615)
            at android.view.ViewGroup.dispatchSaveInstanceState(ViewGroup.java:2615)
            at android.view.View.saveHierarchyState(View.java:12842)
            at com.android.internal.policy.impl.PhoneWindow.saveHierarchyState(PhoneWindow.java:1709)
            at android.app.Activity.onSaveInstanceState(Activity.java:1204)
            at android.support.v4.app.FragmentActivity.onSaveInstanceState(FragmentActivity.java:523)
            at android.app.Activity.performSaveInstanceState(Activity.java:1153)
            at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1223)
            at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:3265)
            at android.app.ActivityThread.handleStopActivity(ActivityThread.java:3324)
            at android.app.ActivityThread.access$1100(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1273)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:212)
            at android.app.ActivityThread.main(ActivityThread.java:5137)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:902)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:718)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by ksoichiro** [comment] 2015-01-20 12:29
Thank you for your information.
I fixed the issue.

**Comment by PankovSerge** [comment] 2015-01-20 12:42
Issue was fixed, checked on devices with 4.1.2 - 5.0. 
Thanks for your work, ksoichiro. 
Best regards, Pankov Serge

**Comment by ssppgit** [comment] 2015-01-26 20:52
Hi @ksoichiro ! although this was fixed, gradle dependecy is wrong. I suppose you have to update this because we don't see CacheFragmentStatePagerAdapter in the dependencies.

Thanks!

**Comment by ksoichiro** [comment] 2015-01-28 15:51
@ssppgit Sorry for dependencies problem. I released it as v1.5.0 and it's available on Maven Central.

**Comment by ssppgit** [comment] 2015-01-28 21:13
@ksoichiro Thanks guy!!! :)

**Comment by ksoichiro** [comment] 2015-02-02 16:03
It seems it's solved, so I'll close this issue.
Please reopen it or open a new issue if you have any problems.

**Closed by ksoichiro** 2015-02-02 16:03 UTC
